### ISSUE TITLE
Authentication integration

### ISSUE THREAD

**Issue by pixtim** [hansehe/graphql-gateway#1]
I'm using this chart as my GraphQL federated gateway.

I've started integrating Keycloak with my Kubernetes application. The Angular front-end redirects to the Keycloak login to get the necessary tokens. The cookies will then be passed along so that the Keycloak client can do the auth-n/z checks against the Keycloak server.

The gateway's Playground UI doesn't have a login redirect so requests are denied. Is there a way I can register a Keycloak client with the gateway and configure the login redirect? I'm hoping that the tokens will then be passed along to the federated services when I test the API via the Playground UI.

Thoughts?

Thanks for the helm chart. It makes it really easy to spin up a federated gateway. :smiley_cat:

**Comment by hansehe** [comment]
Hi, and great to hear that the chart helps you out! :)

The gateway service is mainly a wrap around the open source graphql libraries which includes the playground, so I cannot do that directly. If anything, you will have to do a PR to https://www.npmjs.com/package/apollo-server-express to enable this feature, and then I can include it with this service.

From my experience, I have solved it by logging in through another service to get the access token and then include it with the headers in the graphql playground.
